### ISSUE TITLE
default middleware needs to be able to set the gzip caching folder

### ISSUE THREAD

**Issue by gregwebs** [yesodweb/yesod#1012]

**Comment by snoyberg** [comment]
I don't think this should be in the default middleware, since caching gziped content is not always the right behavior. Users have the ability to customize their middleware to use a cache folder, I believe that's sufficient.

**Comment by gregwebs** [comment]
This is a point of confusion for users. What do you think about adding a gzip caching folder to the default scaffold?

**Comment by snoyberg** [comment]
I think users is a bit of an exaggeration to be honest. Most people seem
fine with the default. I have no problem with changing the scaffold- or
even changing the default at since point- but I think a simple comment is
probably sufficient for now.

Simple comment probably suffices for many of the older issues I closed out
to be honest
