### ISSUE TITLE
yesod-core update seems to have broken git-annex

### ISSUE THREAD

**Issue by mdorman** [yesodweb/yesod#1059]
Even though it's git-annex that fails to build, I'm raising this issue here because it seems unlikely to be a truly git-annex specific issue (though [I have also logged it in git-annex's bug tracker](http://git-annex.branchable.com/bugs/Build_failures_with_7.10/)) 

Anyway, the Nix build job for git-annex started failing yesterday, with the following error ([full build log](http://hydra.cryp.to/build/1099681/nixlog/1/raw)):

    Assistant/WebApp/Types.hs:39:1: ‘WebApp’ is not in scope at a reify

This failure coincided with pulling yesod-1.4.14 (41f217351e9e81a618ce4de9abb1e2efa56ae9ed being that commit) into nix.

As I said, I realize it may actually be a git-annex at fault, but it went from building to broken as a consequence of the yesod upgrade, so it seems like at least something you might want to warn your users to check regarding their apps.

**Comment by creichert** [comment]
This could coincide with 9991e307e3ba3caa83d44fdfcc705e2b679676d8 - ea62a38464eb4c22fa4d100f387bd22720d72b67 which seem to have been merged right before the release. 

For reference: https://github.com/joeyh/git-annex/blob/master/Assistant/WebApp/Types.hs#L39

**Comment by gregwebs** [comment]
@Daniel-Diaz can you take a look at this?

**Comment by Daniel-Diaz** [comment]
@gregwebs I'm looking into it. It really seems related to my changes.

**Comment by Daniel-Diaz** [comment]
If you place the ``data`` definition _above_ the ``mkYesodData`` TH call, the mentioned code compiles. In order to use a type in TH you have to define it above. Otherwise, the type is not in scope at the time of generating the splice.

**Comment by gregwebs** [comment]
So did the changes require the data definition to be placed above now? Was it a GHC accident that it worked before?

**Comment by Daniel-Diaz** [comment]
It's because of the use of ``reify``, which is mentioned in the error. ``mkYesod`` (and variants) didn't use ``reify`` before. This is needed for the new feature - accepting types with parameters as yesod site types. Function ``reify`` extracts information about a type that must be already in scope at splicing time.

**Comment by Daniel-Diaz** [comment]
Sorry, I didn't think about this breaking change when I wrote the patch, and instinctively defined the type before using it in all my tests.

**Comment by gregwebs** [comment]
No problem. Can you add a mention of this issue to the [Changelog](https://github.com/yesodweb/yesod/blob/master/yesod-core/ChangeLog.md#1413) ?

**Comment by Daniel-Diaz** [comment]
OK. I guess I'll add it to 1.4.14, and change the "Add mkYesodGeneral, which allows creating sites with polymorphic type parameters" message which is partially wrong and should be under 1.4.14 as well, right?

**Comment by snoyberg** [comment]
I don't know if it's possible, but could we catch the exception in th and
fall back to the old behavior?

**Comment by Daniel-Diaz** [comment]
@snoyberg I think something can be done... Let me take a look.

**Comment by Daniel-Diaz** [comment]
@snoyberg I made it so that when the type is not in scope at splicing time, the type is considered of arity zero, thus avoiding the call to ``reify``. The commit is: https://github.com/Daniel-Diaz/yesod/commit/e77f6bd7099f4249c7961f794a7f1fd27921bece

However, I feel like it is confusing from the user point of view, as they'll get a different result depending on the ordering of the code. Right now it forces to one option (i.e. type before TH call), but it also gives you only one possible result.

Any thoughts on this? I'm opening a PR, but before merging I would like this to be considered.

**Comment by gregwebs** [comment]
@Daniel-Diaz I would agree if we were starting from scratch. However the change you are making sounds like a net improvement because of backwards compatibility.
