### ISSUE TITLE
Auth is a bit confusing to newcomers.

### ISSUE THREAD

**Issue by lethjakman** [yesodweb/yesod#1062]
It'd be really nice to have some example code for the auth methods such as Yesod.Auth.GoogleEmail2 and such. It may not be clear to newcomers (such as myself) how to properly pass parameters in and securely store keys.

**Comment by creichert** [comment]
I think some documentation updates to the Auth could be a great improvement. Have you made any progress with GoogleEmail2? If so, maybe you could update the docs with some of your findings.

**Comment by lethjakman** [comment]
I haven't made progress with GoogleEmail2 yet, I started working with Email and mime-mail-ses instead. It is, however, in my plans to work with GoogleEmail2. As I learn more about the above I will attempt to add some documentation assuming no one beats me to it.

**Comment by jezen** [comment]
As a newcomer, I am finding authentication with Yesod to be *very* confusing. What I'm finding possibly even more confusing is the aversion to use email authentication with Yesod, because it supposedly pulls in more dependencies.

I can't understand being worried about dependencies, but at the same time suggesting all Yesod users would be happy depending on third party authentication stuff.

I'm not sure it's a good approach to suggest just passing email down to sendmail either. Heroku doesn't provide sendmail.

**Comment by lethjakman** [comment]
I have an example of direct email authentication that uses SES to mail you; sendmail is never reliable in my experiences. I've been meaning to isolate that into an example, would that be helpful to you?

**Comment by jezen** [comment]
@lethjakman That'd be *very* helpful. Thanks!

**Comment by lethjakman** [comment]
I added an example in PR #1116. I hope that helps!

**Comment by jezen** [comment]
@lethjakman Excellent! Thanks so much for this!

![](http://gifs.joelglovier.com/excited/42-Snoop-Bounce.gif)

**Comment by lethjakman** [comment]
No problem! I hope that helps you get started.

**Comment by StevenXL** [comment]
See #1116
