### ISSUE TITLE
Documentation bug: enabling foreign key checking in SQLite

### ISSUE THREAD

**Issue by ianthehenry** [yesodweb/yesod#1242]
After read [this wiki page](https://github.com/yesodweb/yesod/wiki/Activate-foreign-key-checking-in-Sqlite), I have a dumb question: where does the *pool* part of `createSqlPool` come from?

It seems to me that, with the current example, no matter how many connections you specify should be available in the pool, you are always going to get back the single connection you put into it -- for there is only one time when the connection is created. And possibly that connection is going to be used after closing it.

It seems to me that the following would be correct:

```haskell
createSqliteBackend :: Text -> LogFunc -> IO SqlBackend
createSqliteBackend dbPath logFunc = do
  conn <- Sqlite.open dbPath
  disableForeignKeys conn
  wrapConnection conn logFunc
```

And elsewhere:

```haskell
let dbPath = sqlDatabase $ appDatabaseConf appSettings
pool <- flip runLoggingT logFunc $ createSqlPool
    (createSqliteBackend dbPath)
    (sqlPoolSize $ appDatabaseConf appSettings)
```

I'm hesitant to make this change myself because I'm so new to persistent: it seems likely to me that I'm misunderstanding something and my diagnosis and proposed fix is not correct.

**Comment by MaxGabriel** [comment]
Hi, I wrote this documentation, and I don't think this is a dumb question at all. I haven't tested this, but just from looking at the code, I think you're completely correct.

👍 

Would you be up for updating the wiki with your findings?

**Comment by psibi** [comment]
Note that the cookbook documentation has moved to it's own repository: https://github.com/yesodweb/yesod-cookbook

The corresponding cookbook page mentioned in the issue is present here: https://github.com/yesodweb/yesod-cookbook/blob/master/cookbook/Activate-foreign-key-checking-in-Sqlite.md

Please make your changes there. I have also updated each page in the wiki cookbook pages about the new location of the cookbook to avoid further confusions.

**Comment by ianthehenry** [comment]
Done here: https://github.com/yesodweb/yesod-cookbook/pull/9
