### ISSUE TITLE
Log request and response

### ISSUE THREAD

**Issue by lippling** [yesodweb/yesod#1276]
How can I log request and response headers/bodies when the status is 4xx oder 5xx?

I have this scaffolded function:

```haskell
makeLogWare :: App -> IO Middleware
makeLogWare foundation =
    mkRequestLogger def
        { outputFormat =
            if appDetailedRequestLogging $ appSettings foundation
                then Detailed True
                else Apache
                        (if appIpFromHeader $ appSettings foundation
                            then FromFallback
                            else FromSocket)
        , destination = Logger $ loggerSet $ appLogger foundation
        }
```

**Comment by snoyberg** [comment]
You'd need to handle that manually, the logging middleware doesn't have that support out of the box. Keep in mind that, in order to make that happen, you'll need to cache the entire request body contents for every request, since you won't know until _after_ the application has consumed the request body if you want to log it.

The code inside the logging middleware module gives some examples of how to do this kind of caching, and could be a good basis for a custom middleware.

**Comment by lippling** [comment]
Ok thanks!
I'll think about it...
