### ISSUE TITLE
Streaming pathtracer

### ISSUE THREAD

**Issue by lobachevzky** [yesodweb/yesod#1434]
I have written a pathtracer in Haskell and I would like to display the pathtraced images in a browser. My goal is for the image to dynamically change as follows:

1. The pathtracer should iterate continuously and the image should update accordingly in the browser.
2. The camera should be able to zoom and pan.
3. Objects in the image should move in response to mouse clicks.

I have read most of the yesod book and several of Mr. Snoyman's posts and presentations on conduits. However, I am a little new to web programming. These are my questions:

1. Is Yesod a good tool for this or am I better off using a GUI-based approach, using libraries like Yampa, Reflex, or Reactive Banana?
2. If I use Yesod, how would I actually get the image to update live? I have experimented a little with `respondSource` but I do not understand how to write streams to HTML content.

I have mostly been experimenting with the following simple example:

```haskell
data HelloWorld =
  HelloWorld

mkYesod
  "HelloWorld"
  [parseRoutes|
/ HomeR GET
|]

instance Yesod HelloWorld

getHomeR :: Handler TypedContent
getHomeR =
  respondSource "text/csv" $ do
    sendChunkText "number,plus1\n"
    forM_ [1 .. 100 :: Int] $ \i -> do
      threadDelay 1000000
      sendChunkText $ mconcat [tshow i, ",", tshow (i + 1), "\n"]


main :: IO ()
main = warp 3000 HelloWorld
```

As I'm sure you know, this just downloads a file when you navigate to `localhost:3000` in the browser. How would I get the browser to actually display this stream of numbers? Is this even the right starting point to eventually get a stream of images from my pathtracer to show up in a browser? 

Thanks for your advice. Long live Haskell.

**Comment by snoyberg** [comment]
In order to make this work in a web application, it sounds to me like you'll need to:

* Write some client-side code (either Javascript, or a language that transpiles to Javascript like PureScript or GHCJS-Haskell) that can render the image
* Write some server-side code (this is the Yesod) bit that generates the data for the path tracer
* Set up communications between the server and client in a streaming fashion

There are three common ways for achieving that streaming communication:

* WebSockets https://www.stackage.org/package/yesod-websockets
* Event streams/server-sent events https://www.stackage.org/package/yesod-eventsource
* Long polling

The third is the oldest technique, but has been mostly superseded by the other two. WebSockets allow for bidirectional communication, meaning that the client can send data to the server as well as the server sending data to the client. Personally, I prefer event streams for the case that you need unidirectional communication (which sounds like your case), especially since they play more nicely with proxies and load balancers.

All of that said: this kind of situation may be simpler as a desktop GUI if you're already familiar with such frameworks. Doing this in a web app will entail learning quite a few different things at once. That said, all of the pieces should be present, and I'm sure people on the mailing list in particular would enjoy providing feedback on this kind of a topic.

> Long live Haskell.

👍

**Comment by lobachevzky** [comment]
Yeah, I am working on a websocket-based approach. Talking to a friend, he thought it would be more efficient to implement this using a video, since the canvas updates are frequent but the user interactions are infrequent. What are your thoughts on this? 

I am not sure how to get Yesod to dynamically generate the content of a video instead of a static file. Would I need to implement a custom handler? Is there a way to generate a video using a conduit?

**Comment by snoyberg** [comment]
I have no experience generating video content in a streaming fashion. There are likely libraries for it, but I'm not familiar with them.

**Comment by lobachevzky** [comment]
Ok. No worries. Maybe working on some kind of video streaming capability for yesod might become a long-term project.
