### ISSUE TITLE
Yesod 1.4 missing conduit upper bounds

### ISSUE THREAD

**Issue by andrewthad** [yesodweb/yesod#1513]
The 1.4.* series of yesod-core does not build against conduit-1.3.*.  I would like to add this missing upper bound with a cabal revision. I am not sure if yesod  has a policy around this or not.  I know it would be tedious, since there are a bunch of releases that would need to be tweaked. I would be happy to do it if I were temporarily made a hackage maintainer.  If there is a policy  against revisions, feel free to close this out.

**Comment by andrewthad** [comment]
I got a little further building this and found that yesod-core-1.4.* doesn't build against base-4.11 because Semigroup is now a superclass of Monoid. It would be nice to have a final release in the 1.4 series that made it buildable against base-4.11. All the other releases in the 1.4 series could have their upper bounds on base appropriately set to `< 4.11`

Also, it might be better to just deprecate most of the releases in the 1.4.* series. This would prevent the solver from trying to use them, and then there would be no need to do revisions for them. We could leave the ones that are part of LTS releases undeprecated.

**Comment by snoyberg** [comment]
Overall, I'm not personally interested in solver errors, since I don't
recommend using the solver. If you'd like Hackage rights to add revisions,
I'm OK with that, but I'm not in favor of deprecations. They confuse the
display, aren't accurate (since those versions in a Stackage release are
still supported), and don't really help that much with the solver anyway.

I'm also OK with a release in the 1.4 line, are you interested in sending a
PR for that?

Let me know your Hackage username and I can give you maintainer rights.

**Comment by snoyberg** [comment]
Maintainer rights granted on Hackage.

**Comment by andrewthad** [comment]
The revisions have been made to everything in the 1.4 series. I'll work on a 1.4.37.4 at some point this weekend.

**Comment by andrewthad** [comment]
I ended up needing to put a minimum bound for `conduit-extra` in place (`>= 1.1.7`), and I also bumped everything to accept `vector-0.12`.

**Comment by jezen** [comment]
Judging by the discussion, this appears to have been resolved out of band, so I will close this issue.
