### ISSUE TITLE
requireJsonBody is vulnerable to XSS, is the wrong default and should be deprecated

### ISSUE THREAD

**Issue by eborden** [yesodweb/yesod#1575]
`requireJsonBody` is open to XSS attacks through `text` and `form` mime types and can lead to privilege escalation. This is the wrong default for `yesod` to have and leads users into the lion's den. This function should be deprecated in favor of the safer alternative, `requireCheckJsonBody`. The insecure version can still be supported as `insecureRequireJsonBody` for users that need it.

**Comment by snoyberg** [comment]
I'm not opposed to a deprecation, the original functionality was clearly a
mistake on my part. However, I'm not seeing the attack vector you mention,
could you provide some more details?

**Comment by MaxGabriel** [comment]
There is a potential attack vector in that the browser [does not trigger CORS requests for "simple requests"](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests), which includes POST requests that are form or text content-types. An attacker can craft [a form whose body is valid JSON](https://docs.spring.io/spring-security/site/docs/4.2.x/reference/html/csrf.html#csrf-protection-and-json), and when a user visits attacker.com and submits that form, it can be submitted to bank.com and bypass CORS.

Checking the content-type is `application/json` prevents this, because if the content-type was set to `application/json`, then the browser would send a CORS request—a preflight OPTIONS request to the server asking if the current domain (and some other values) are whitelisted to send requests to that server. If the server doesn't say attacker.com is whitelisted, the browser will not send the real request to the server.

I would describe this as a CSRF attack, not XSS, though.

It's worth noting that this attack vector does not apply to an API service not intended to serve browsers—if your customers are hitting an API from say curl or a Ruby script, those clients don't do CORS checks (not being in a browser, they don't have origin domains). This might impact how the API should be named/what a potential deprecation message should be.

**Comment by snoyberg** [comment]
Thanks for clarifying! Would one of you be able to PR a fix?

**Comment by MaxGabriel** [comment]
I'll let @eborden take it if he would like, otherwise I'll do it

**Comment by eborden** [comment]
Thanks for jumping in with the details @MaxGabriel. I'll put a PR together today.
