### ISSUE TITLE
Routes with different methods should not overlap

### ISSUE THREAD

**Issue by dkurochkin** [yesodweb/yesod#44]
Hello.

It feels there is no reason for for routes with different methods to overlap, e.g.

<pre>
/ RootR GET
/ PostRootR POST
</pre>

I imagine the following use case:

<pre>
/#String RegularR GET -- general handler for GET requests
/create PostR POST -- this URL supports POST
</pre>

As a workaround, RegularR can handle both GET and POST, and POST handler would check if POST is indeed allowed for an URL.

BTW Thanks for a great framework! I am just starting learning it, looks very nice so far.

Regards,
  Dmitry

**Comment by pseudonom** [comment]
We have a slightly different use case:

```
/#[FooId] FooR GET
/#FooId FooR POST
```

i.e. We'd like to be able to be able to specify different URL types of parameters for the same resource depending on the method. Is that use case compelling enough that you'd accept a pull request to add per-method disambiguation?

**Comment by chreekat** [comment]
@pseudonom the OP's idea creates one kind of ambiguity between resources and their identifiers: same identifier, different resources. Yours creates another kind: different identifiers, same resource. Since Yesod maps resources to datatypes, your idea would require working around the type safety and simplicity of that scheme! In contrast, OP's idea merely requires relaxing some TH-runtime checks.

Would query parameters work instead?
