### ISSUE TITLE
Some documentation / a tutorial for running Yesod in GHCi would be really appreciated

### ISSUE THREAD

**Issue by simg** [yesodweb/yesod#763]
The thing that is most slowing down my learning of Haskell / Yesod is my inability to do interactive debugging. Surprisingly, there doesn't seem to be any clear tutorials (or even any tutorials?) about how to go about doing this with Yesod.

I've found this: https://github.com/chrisdone/ghci-reload-demo which seems ideal in terms of developer friendliness but I'm having difficulty getting it to work.

I've installed the foreign-store-0.1 module, updated my scafford with app/DevelMain.hs and updated my .cabal file with warp and foreign-store as suggested. 

I can successfully set breakpoints in my target code but I'm failing at the last hurdle which is being able to run DevelMain. This is almost certainly my total lack of knowledge but I'm sure I can't be the only one who is / will struggle with this?

```:l DevelMain.hs``` (and various combinations like app.DevelMain.hs etc) all fail with "Failed, modules loaded: none"

I've added a **TODO into this [wiki page](https://github.com/yesodweb/yesod/wiki/ghci) (hope you don't mind). If someone were to help me get ghci debugging working, I'd be happy to turn the experience into some decent (ie beginner level) documentation for the wiki :)

Many thanks

**Comment by MaxGabriel** [comment]
I've updated the wiki page with instructions on:

1. Running database/handler actions from GHCi
2. Using the debugger with Yesod (both by executing a function with a breakpoint in it from GHCi + hitting a handler function from a browser).

 For hitting a breakpoint from a browser, I wasn't able to use DevelMain (I get this [`*** Ignoring Breakpoint`](https://github.com/ghc/ghc/blob/e76f86646229b3f8bcdc6ad71d464104c639f431/compiler/main/InteractiveEval.hs#L459) message, potentially because it's running the app in a new thread so it's not considered to be running interactively, so instead I used `Application.appMain`). 

If I understand the DevelMain correctly, the main goal is to achieve faster app reloads than `yesod devel` provides? I left the DevelMain/Killing Threads sections mostly untouched, regardless.

**Comment by simg** [comment]
Thanks Max, that looks very helpful.

**Comment by geraldus** [comment]
@MaxGabriel can you share a link to mentioned wiki page, can't find it myself. Thanks.

**Comment by MaxGabriel** [comment]
Sure @geraldus, its this page https://github.com/yesodweb/yesod/wiki/ghci

Stuff is pretty hard to find on the wiki :/

**Comment by pm0kjp** [comment]
I used stack to build my application, and I'm trying to do debugging as well.  Stack exec ghci does give me a repl, but I'm not sure what do do next.  Total n00b here.  I have a 500 error on one handler I'm trying to debug and I'm clueless as to how (I inherited this application, I normally use php for web).
