### ISSUE TITLE
Cannot install yesod-bin with recent binary

### ISSUE THREAD

**Issue by xenog** [yesodweb/yesod#900]
Due to the dependency between yesod-bin and ghc, in my system I cannot install yesod-bin if I have packages installed which depend on a recent version of binary.  In Ubuntu 14.10 ghc comes with binary 0.5, but the haskoin package requires binary 0.7.  When attempting to install yesod-bin in a system that has haskoin, it is unable to resolve dependencies.

```
$ cabal install ~/src/haskoin ~/src/haskoin-wallet yesod-bin
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: haskoin-0.1.0.3 (user goal)
next goal: binary (dependency of haskoin-0.1.0.3)
rejecting: binary-0.5.1.1/installed-72e... (conflict: haskoin => binary>=0.7
&& <0.8)
trying: binary-0.7.2.3
trying: yesod-bin-1.4.3.3 (user goal)
trying: ghc-7.6.3/installed-494... (dependency of yesod-bin-1.4.3.3)
next goal: bin-package-db (dependency of ghc-7.6.3/installed-494...)
rejecting: bin-package-db-0.0.0.0/installed-608... (conflict: binary==0.7.2.3,
bin-package-db => binary==0.5.1.1/installed-72e...)
Backjump limit reached (change with --max-backjumps).
```

**Comment by snoyberg** [comment]
You have three options here:

* Install yesod-bin and haskoin separately. Since yesod-bin is only providing a binary, this shouldn't result in any problems.
* Ask the haskoin author to support the older binary.
* Upgrade to GHC 7.8, preferably following [the Stackage installation instructions](http://www.stackage.org/install).

I'd recommend the last approach. In any event, there's nothing I'm aware of that yesod-bin can change to accommodate this request, so closing the issue.

**Comment by xenog** [comment]
Thanks Michael!

I am the author oh haskoin.  ;)

I will install GHC 7.8 using Stackage.  It looks like the best approach.
