### ISSUE TITLE
Query string support in route handler WAS: Add handler to treat query parameter lookup as JSON object

### ISSUE THREAD

**Issue by spl** [yesodweb/yesod#918]
(This issue is more to present the idea and get feedback on it, not necessarily to request this exact function.)

I think dealing with the query string should be as easy as dealing with a JSON body. So, I wrote a hack to translate the query string to an instance of `FromJSON`:

``` haskell
-- | Parse a set of GET parameters as if they were a JSON object. That is, treat
-- the query string 'a=b&c=7&d=true' as the object '{"a":"b","c":7,"d":true}'.
--
-- Note that you probably don't want to use this with nested JSON objects
-- because the inner objects will be actual JSON in the GET parameters.
requireGetJson :: (MonadHandler m, FromJSON a) => m a
requireGetJson = do
    qs <- queryString . reqWaiRequest <$> getRequest
    case fromJSON $ object $ mapMaybe toPair qs of
        Error err -> invalidArgs ["parse failed:", pack err]
        Success x -> return x
  where
    toPair (k, mv) = (decodeUtf8 k,) <$> join (fmap (decode2 . LB8.fromStrict) mv)
    -- If decoding fails, trying decoding as if it's a string.
    decode2 s = decodeV s `mplus`
                decodeV (LB8.singleton '"' <> s <> LB8.singleton '"')
```

This uses an adapted version of `decodeV` from `aeson-utils` (silkapp/aeson-utils#2).

If there are other ways to simplify query parameter lookup, I'd love to hear them. For now, this seems to work, though naturally the nested object part leaves me with a dirty feeling.

**Comment by gregwebs** [comment]
[servant](http://alpmestan.com/posts/2014-12-09-rethinking-webservices-apis-haskell.html) has query strings properly integrated into the routing. You could look at how they parse it into a Haskell data structure.

**Comment by spl** [comment]
Yes, servant is nice.

**Comment by snoyberg** [comment]
Let's just integrate it already in the yesod routing syntax, it shouldn't
be that hard. I can take a crack at it after I'm back home and, of course,
after I catch up on my ridiculous backlog.

**Comment by spl** [comment]
> Let's just integrate it already in the yesod routing syntax, it shouldn't be that hard.

@snoyberg Sorry, what is _it_?

**Comment by gregwebs** [comment]
Query parameters that can be parsed into Haskell data

**Comment by snoyberg** [comment]
To clarify, here's what I'd like to see:

```
/ HomeR GET
/foo FooR GET
/foo/#Word?bar=#Int&baz=#Text Foo2R GET

Foo2R :: Word -> Int -> Text -> Route App
getFoo2R :: Word -> Int -> Text -> Handler Html
```

Does that sound reasonable?

**Comment by gregwebs** [comment]
Maybe could be a better default: otherwise it could be part of the url

**Comment by ajnsit** [comment]
Hi, did this get left out? I recently thought of adding something similar for wai-routes and stumbled upon this issue.

**Comment by snoyberg** [comment]
This has not yet been implemented.

**Comment by jkarni** [comment]
Is anyone working on this? If not, I can.

**Comment by snoyberg** [comment]
I don't think anyone's started on this (if they have, they haven't mentioned it to me). If you want to attack this, that would be great!

**Comment by ajnsit** [comment]
Yup, I'm not working on it. Feel free to take it up!

**Comment by jkarni** [comment]
I got this mostly working, but before making a PR there are a few things that are worth discussing.

- @snoyberg suggested `/foo/#Word?bar=#Int&baz=#Text Foo2R GET`, and this looks good to me. But should it be possible to describe query params in a hierarchy prefix? It would seem convenient, but on the other hand that suggests query params can appear elsewhere than at the end of URLs.
- If query params can appear elsewhere, should the handler get arguments in the order they appear in the URL? Or all query params after all captures?
- `Maybe` by default? Any syntax for making it required? I think I'd rather not implement both in this PR, but the syntax decisions should probably keep in mind the question. And should it really be `Maybe`? An isomorphic type might be nicer since then the handler type will make it a little clearer where data is coming from (capture vs. query)
- Overlap checking. If for now every query param is optional, then all paths that would otherwise overlap will continue to overlap. So my intuition is that for now overlap checking should ignore query params, and stay the way it is. But I could be missing something.

**Comment by spl** [comment]
Since the route parts (e.g. the `#Word` in `/foo/#Word`) already define a required argument, I would suggest assuming that the query parameter is an optional argument. That is, the signatures would be:

```
/foo/#Word?bar=#Int&baz=#Text FooR GET
```

```haskell
FooR    :: Word -> Maybe Int -> Maybe Text -> Route App
getFooR :: Word -> Maybe Int -> Maybe Text -> Handler Html
```

And I do think `Maybe` is the appropriate type choice here.

**Comment by jkarni** [comment]
Oh, one other thing - having:

```
data Query a = Query a | NotPresent | NotParsable Text
```
instead of `Maybe` allows distinguishing queries that are present but not parsable from those that are not at all present.

**Comment by jkarni** [comment]
The other thing is that I'm using `fromPathPiece/toPathPiece` for encoding and decoding. This is, I think, okay, but we may want to consider distinguishing between query and path decoding and encoding (and maybe switching to [`http-api-data`](http://hackage.haskell.org/package/http-api-data)).

**Comment by snoyberg** [comment]
* I wouldn't include hierarchy stuff, at least for now. It seems like it could be added later
* Let me ask a broader question: what's the expected behavior if a query string parameter that is intended to be required is left out, or has an incorrect type? It doesn't seem reasonable to return a 404 or any other error code.
* I agree on leaving out overlap checking for now

**Comment by jkarni** [comment]
> Let me ask a broader question: what's the expected behavior if a query string parameter that is intended to be required is left out, or has an incorrect type? It doesn't seem reasonable to return a 404 or any other error code.

Agreed. On the other hand, in `servant` not distinguishing between missing and not parseable has annoyed some people.

**Comment by snoyberg** [comment]
What _does_ servant do in the two possible error cases?

**Comment by jkarni** [comment]
Right now it doesn't distinguish between them, though there's an [open issue](https://github.com/haskell-servant/servant/issues/241) about that.

**Comment by snoyberg** [comment]
But suppose the API states an `Int` will be the value for a query string and nothing is present, does servant return a 404?

**Comment by jkarni** [comment]
No, the handler just gets a `Nothing`.

**Comment by gregwebs** [comment]
404 or any error code would be better than Nothing

**Comment by snoyberg** [comment]
I'm OK with a 400 status code approach.

**Comment by jkarni** [comment]
OK, my initial approach was just to make query params very much like captures. This meant that if a capture couldn't be decoded *and* the method was incorrect, a 400 was returned instead of a 405. In my opinion 405s should always take priority (over 400, though not 404), so I started working on moving the query params further into the code so they occur later. This isn't quite as clean, and has a couple of issues - primarily, that it's no longer always possible to return the route datatype in case the method doesn't match. This is a backwards incompatible change, and while we could check whether query params are needed (or even try parsing them even though there was a method mismatch) in order to keep current code as is, it may be a little unintuitive to have the access to the datatype depend on something that happens conceptually (and actually) *after* the method has been checked, and which can sometimes fail.

Before continuing, I wanted to check if anyone had strong opinions about directions - e.g. if treating query params just like captures is better.

**Comment by gregwebs** [comment]
The way I would use query params is that the route matches regardless of the params. If a param is required and not present than give a 4xx error (not a 404, not sure what is best).
But I would be happy with any query param support.

**Comment by spl** [comment]
I'm afraid I'm not following all the details. Here are my thoughts on an initial straightforward but flexible specification:

* Query parameters should be optional, allowed in any order, and support an optional value.
* All query parameters should still be available to `lookupGetParam`.
* There could be query parameters not mentioned in a `routes` file but used by `lookupGetParam`.
* Allow the app to decide how to handle the parameters that are expected but missing. This matches the current flexibility of using `lookupGetParam` in the handler.
* If a parameter value is present but failed to parse, I would consider it missing. If I want to look at the text value, I can use `lookupGetParam` to get it.
* I would expect a `Maybe a`-like type for an optional parameter with `Just` a parsed value (and `()` could be used for no value expected).

That's what I would consider a first implementation that would give me additional useful features without taking anything away.

Supporting required parameters is an added bonus because it means I don't have to deal with it. For that, you could respond with a 400 if the parameter is missing. If the parameter is present, I would still expect a `Maybe a`-like type with `Nothing` for unparsed data, since I can look up the text with `lookupGetParam`. An alternative is `Either Text a` with the unparsed value in `Left`, but I don't think this is necessary.

I think dealing with unparseable values is an error reporting issue, and it would depend on the app how I deal with it. Fortunately, I can already deal with it as I like using `lookupGetParam`.

**Comment by gregwebs** [comment]
How would we

> Allow the app to decide how to handle the parameters that are expected but missing.

**Comment by spl** [comment]
@gregwebs By that, I mean that the interface would assume the query parameter are optional but the app may require it. Therefore, supposing the handler received `Maybe a` for some parameter, where `Nothing` meant that the parameter was missing, then, in the handler, when you get a `Nothing`, you could respond with a 400 if you wanted or with any other response that was appropriate. It would be the same thing you would do using `lookupGetParam`. The difference here is that the parameter value is parsed.

**Comment by jezen** [comment]
The discussion here is inactive, so I will close this.
