### ISSUE TITLE
Purescript?

### ISSUE THREAD

**Issue by JulianLeviston** [yesodweb/yesod#930]
What about purescript as an idea for frontside? I noticed its absense in your wiki about the subject. http://www.purescript.org

**Comment by gregwebs** [comment]
Can you add it to the wiki?

**Comment by JulianLeviston** [comment]
Sure

**Comment by JulianLeviston** [comment]
Done. Added a couple of other things in, too. Wasn't 100% sure of how much liberty I had. Hope I didn't overstep.

**Comment by JulianLeviston** [comment]
Also, what about perch? https://github.com/agocorona/haste-perch

**Comment by gregwebs** [comment]
The more wiki contributions the better.

**Comment by JulianLeviston** [comment]
Awesome. Ok... tho I really do think it'd be advisable if you had some guidelines for contribution... (What? Am I suggesting a "type" system here? ;-) hehe). The reason being that then people will know both what is required of them in terms of content creation, and also how to read what is there: how to pick between authoratitively condoned ideas and those just written on the whim of someone new to Haskell (such as myself). In other words, the concept of "weightedness" of content.

**Comment by gregwebs** [comment]
Wikis don't provide any tools to do this (or actually anything that is actually important about authoring content), which is why wikis generally suck.

The main approach I have seen is people leaving a note that a certain section is their opinion or that they agree with another one.

I am open to more ideas. One thing I have been doing is using a github repo rather than a wiki (you can link between markdown files). This way you can pull request changes. But that overhead would be a bit much for some types of content on the Yesod wiki, and we do already have this to an extent from the Yesod book.
