### ISSUE TITLE
Request 404, missing bootstrap.css.map

### ISSUE THREAD

**Issue by netroby** [yesodweb/yesod#934]
```
GET /static/css/bootstrap.css.map
  Accept: */*
  Status: 404 Not Found 0.000122s
```

**Comment by netroby** [comment]
The quickstart guide is ok, but the css.map file missing. please add it .

**Comment by MaxGabriel** [comment]
@netroby Since the yesod scaffolding isn't compressing the CSS, it doesn't seem like it should need the sourcemap. If we just remove [this line](https://github.com/yesodweb/yesod-scaffold/blob/bb7897b67021f42aa38c7f2fedd03be81f8980c9/static/css/bootstrap.css#L6203) from bootstrap.css, that appears to stop Chrome from trying to load the `.map` version.

Alternatively the `.map` file could be added to the scaffolding like you suggested; not sure which approach is preferable.

**Comment by zudov** [comment]
In firefox I can disable option "Show original sources" and it won't be trying to fetch `.map` files. It might be that chrome also has such an option.

IMHO, the right approach is to either add actual map files for bootstrap, or disable that feature in the browser if you don't need one.

**Comment by netroby** [comment]
Thanks for you guys comment. I report this , because we thought there should not be any unusual http code . the only expect http response code should be 200.

Ok, we know there be something not right. we should fix it.

For yesod. I suggest:
1. remove that line by default.
2. add .map file in the same directory together with the css

**Comment by netroby** [comment]
We can easily fix this ,by choose one of the solution.

**Comment by snoyberg** [comment]
Would you be interested in sending a pull request to fix this? It should be
pretty straightforward and a good way to become an official yesod
contributor.

**Comment by MaxGabriel** [comment]
Btw, that PR would go to the [`postgres` branch](https://github.com/yesodweb/yesod-scaffold/tree/postgres) of the [`yesod-scaffold` repo](https://github.com/yesodweb/yesod-scaffold).

**Comment by snoyberg** [comment]
Thanks for pointing that out

**Comment by zudov** [comment]
I guess this issue should be closed now.

**Comment by netroby** [comment]
Ok, let us close it.

**Comment by snoyberg** [comment]
Thanks all!

**Comment by netroby** [comment]
My honor , sir
