### ISSUE TITLE
Overriding host in yesod devel

### ISSUE THREAD

**Issue by ivanperez-keera** [yesodweb/yesod#975]
Yesod devel binds to all interfaces, and ignores the settings files (which may contain specific addresses to bind to).

It would great if one could specify the address to bind to. One use case is to let users play with the application as it is developed while limiting access based on IP. In my case, for example, I am running my app in a controller environment, protecting access using SSL client certificates and running yesod devel with a reverse proxy (all of which is done by apache). I do not want anyone to be able to access the yesod application directly using myIP:3000.

This is what @snoyberg replied: "`yesod devel` doesn't pay attention to the settings file, it takes its instructions on the command line (e.g., -p to tell it port binding). It currently does not support overriding host binding, since it was never intended to be used in anything close to a production setup. Adding such a feature should be relatively straightforward [...]"

For more info, see: https://groups.google.com/forum/#!topic/yesodweb/oIlP4Pd7CsM

**Comment by rzetterberg** [comment]
I have a project that use inside a Docker container (container A). I have port `3000` exposed and use `yesod devel` so that I can test the project in my browser via `http://localhost:3000`. 

The thing is I have a separate Docker container (container B) that contains some acceptance tests that needs to access container A where `yesod devel` is running. To do this I need to link the containers together and use the IP address of container A. 

So I exported the `APPROOT` env var as `http://X:3000` (where X is the containers IP) and ran `yesod devel` in container A. Then I just used that URL in my acceptance tests in container B. Everything seemed to work and the app used the right URL when creating URLs. 

So my understanding is that specifing `APPROOT` to use another URL works as expected, but the issue is that you only want to change what address `yesod devel` binds to so that you can specify which connections are allowed?

**Comment by xamgore** [comment]
Faced with the same problem :+1:

I want to override the host to test my application in the local network (with various mobile devices), but seems that it is not so easy. @snoyberg can you add a `--host` tag to `yesod devel`, please?

**Comment by snoyberg** [comment]
I've just pushed a commit with this change, I'll release to Hackage once Travis completes testing.

**Comment by felipexpert** [comment]
It is not working
